services:
  service-postgres-server:
    image: rtravez/service-postgres-server:latest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - cloud-rtravez
    environment:
      POSTGRES_DB: db_test
      POSTGRES_PASSWORD: admin
  msc-service:
    image: rtravez/msc-service:latest
    ports:
      - "8081:8081"
    volumes:
      - springdata:/tmp
    restart: always
    networks:
      - cloud-rtravez
  msa-service:
    image: rtravez/msa-service:latest
    ports:
      - "1987:1987"
    volumes:
      - springdata:/tmp
    restart: always
    networks:
      - cloud-rtravez
    depends_on:
      - msc-service
networks:
  cloud-rtravez:
volumes:
  pgdata:
  springdata:
