# Perfil desarrollo
server.port=8081
server.servlet.context-path=/mscServices

spring.datasource.url=jdbc:postgresql://localhost:5432/db_test
spring.datasource.username=postgres
spring.datasource.password=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/authorizationServer

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=debug
