#Tomcat Server Basic Config
server.port=8081
server.servlet.context-path=/mscServices
server.max-http-request-header-size=8KB
server.tomcat.max-swallow-size=2MB

spring.datasource.url=jdbc:postgresql://localhost:5432/db_test
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

##Hibernate ORM
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/authorizationServer
# Comma-separated IPs of reverse proxies allowed providing forwarding headers.
app.network.trusted-proxies=127.0.0.1,::1
#spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug
spring.jpa.properties.hibernate.jdbc.lob.non.contextual_creation=true

#Logs
logging.file.name=/tmp/msc-service.log
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=debug