# Perfil producción
server.port=${SERVER_PORT:8081}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/mscServices}

spring.datasource.url=${DB_URL:jdbc:postgresql://service-postgres-server:5432/db_test}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8080/authorizationServer}

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
